export const GoaImages ={
    d1 : require('./port1.jpg'),
    d2 : require('./port2.jpg'),
    db1 : require('./beach1.jpg'),
    db2 : require('./beach2.jpg'),
    dc1 : require('./cult1.jpg'),
    dc2 : require('./cult2.jpg'),
    dh1 : require('./hotel1.jpg'),
    dh2 : require('./hotel2.jpg'),
    dp1 : require('./pack1.jpg'),
    dp2 : require('./pack2.jpg'),
    dp3 : require('./pack3.jpg'),
    dp4 : require('./pack4.jpg'),
    do1 : require('./food1.jpg'),
    do2 : require('./food2.jpg'),
}